# Generated by Django 4.2.23 on 2025-07-31 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organization/workspace', max_length=100)),
                ('subdomain', models.CharField(help_text='Unique subdomain for tenant', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns this tenant', on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants_tenant',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(blank=True, help_text='Optional user subdomain', max_length=255, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='User has verified their email')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Profile creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['subdomain'], name='mysite_user_subdoma_d59c96_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member')], default='member', help_text="User's role in this tenant", max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When user joined this tenant')),
                ('tenant', models.ForeignKey(help_text='Tenant the user belongs to', on_delete=django.db.models.deletion.CASCADE, to='mysite.tenant')),
                ('user', models.ForeignKey(help_text='User who is a member of the tenant', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership',
                'verbose_name_plural': 'Tenant Memberships',
                'db_table': 'tenants_membership',
                'indexes': [models.Index(fields=['user', 'tenant'], name='tenants_mem_user_id_f01927_idx')],
                'unique_together': {('user', 'tenant')},
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subdomain'], name='tenants_ten_subdoma_6c6a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_ten_is_acti_8f654a_idx'),
        ),
    ]
