# Generated by Django 4.2.23 on 2025-08-04 07:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenants_ten_subdoma_6c6a7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenants_ten_is_acti_8f654a_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantmembership',
            name='tenants_mem_user_id_f01927_idx',
        ),
        migrations.AddField(
            model_name='tenant',
            name='members',
            field=models.ManyToManyField(related_name='tenants', through='mysite.TenantMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain can only contain letters, numbers, and hyphens.', regex='^[a-zA-Z0-9-]+$')], verbose_name='subdomain'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
